server:
  port: 5000
logging:
  level:
    root: INFO
    com.company.store_bff: DEBUG
#    org.springframework.web: DEBUG
#    reactor.netty.http.client: DEBUG

spring:
  application:
    name: store-bff

clients:
  base-url: http://localhost:3001
  timeout:
    connection: 5000
    response: 21000
  max-concurrent-requests:
    product-detail: 3
  external-products-service:
    uri:
      product-similar-ids: ${clients.base-url}/product/{productId}/similarids
      product-detail: ${clients.base-url}/product/{productId}


