server:
  port: 5000
logging:
  level:
    root: INFO
    com.company.store_bff: DEBUG
#    org.springframework.web: DEBUG
#    reactor.netty.http.client: DEBUG

spring:
  application:
    name: store-bff

cache:
  similar-products:
    maximum-size: 1000
    expire-after-write: 2m

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 100
        minimum-number-of-calls: 15
        failure-rate-threshold: 70
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 9s
        slow-call-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
    instances:
      productDetails:
        base-config: default

  ratelimiter:
    configs:
      default:
        limit-for-period: 500
        limit-refresh-period: 1s
        timeout-duration: 0ms
    instances:
      productDetails:
        base-config: default

  timelimiter:
    configs:
      default:
        timeout-duration: 10s
        cancel-running-future: true
    instances:
      productDetails:
        base-config: default

clients:
  base-url: http://localhost:3001
  timeout:
    connection: 3000
    response: 10000
  max-concurrent-requests:
    product-detail: 20
  external-products-service:
    uri:
      product-similar-ids: ${clients.base-url}/product/{productId}/similarids
      product-detail: ${clients.base-url}/product/{productId}

app:
  config:
    webclient:
      connection-pool:
        max-connections: 350
        pending-acquire-timeout: 8000
        pending-acquire-max-count: 600
        max-idle-time: 20000
