server:
  port: 5000
spring:
  application:
    name: store-bff



clients:
  base-url: http://localhost:3001
  timeout:
    connection: 1000
    response: 2000
  external-products-service:
    uri:
      product-similar-ids: ${clients.base-url}/product/{productId}/similarids
      product-detail: ${clients.base-url}/product/{productId}
