server:
  port: 5000

spring:
  application:
    name: store-bff

clients:
  base-url: http://localhost:3001
  timeout:
    connection: 12000
    response: 10000
  max-concurrent-requests:
    product-detail: 10
  external-products-service:
    uri:
      product-similar-ids: ${clients.base-url}/product/{productId}/similarids
      product-detail: ${clients.base-url}/product/{productId}


